//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeposWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductPrice
    {
        public long ID { get; set; }
        public string Product_ID { get; set; }
        public string User_ID { get; set; }
        public Nullable<long> Purchase_ID { get; set; }
        public double Price { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Purchase Purchase { get; set; }
        public virtual User User { get; set; }
    }
}
