//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeposWPF.Model
{
    using System;
    using System.Collections.Generic;
    /// <summary>
    /// Class that maps a PurchasePayment to the database
    /// </summary>
    public partial class PurchasePayment
    {
        #region Definition
        /// <summary>
        /// Identifier of the current instance
        /// </summary>
        public long ID { get; set; }
        /// <summary>
        /// Foreign purchase ID
        /// </summary>
        public long Purchase_ID { get; set; }
        /// <summary>
        /// Foreign user ID
        /// </summary>
        public string User_ID { get; set; }
        /// <summary>
        /// Date of the transaction
        /// </summary>
        public System.DateTime Date { get; set; }
        /// <summary>
        /// Value of payment done
        /// </summary>
        public double Payment { get; set; }

        /// <summary>
        /// Mapped instace of purchase
        /// </summary>
        public virtual Purchase Purchase { get; set; }
        /// <summary>
        /// Mapped instace of user
        /// </summary>
        public virtual User User { get; set; }
        #endregion
    }
}
