//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeposWPF.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Linq;
    using System.ComponentModel.DataAnnotations;
    /// <summary>
    /// Class that maps a Sale to the database
    /// </summary>
    public partial class Sale
    {
        #region Constructors
        /// <summary>
        /// Initialize current instance
        /// </summary>
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sale()
        {
            this.SalePayments = new HashSet<SalePayment>();
            this.SaleProducts = new HashSet<SaleProduct>();
        }
        #endregion
        #region Declaration
        /// <summary>
        /// Identifier of current instance
        /// </summary>
        [Display(AutoGenerateField = true, Name = "ID")]
        public long ID { get; set; }
        /// <summary>
        /// Foreign ID of client
        /// </summary>
        [ReadOnly(true)]
        [Display(Name = "Cliente", AutoGenerateField = true, Description = "Validate")]
        public long Client_ID { get; set; }
        /// <summary>
        /// Foreign ID of user
        /// </summary>
        [ReadOnly(true)]
        [Display(Name = "Cajero", AutoGenerateField = true)]
        public string User_ID { get; set; }
        /// <summary>
        /// Date of transaction
        /// </summary>
        [Display(AutoGenerateField = true, Name = "Fecha", Description = "Template")]
        public System.DateTime Date{ get; set; }
        /// <summary>
        /// Date of the purchase
        /// </summary>
        [Display(Name = "Fecha de Pago", AutoGenerateField = true, Description = "Validate")]
        public DateTime PayDate
        {
            get
            {
                return DateTime.Parse(Date.ToShortDateString()).AddDays(CreditDays);
            }
        }
        /// <summary>
        /// Flag that indicates if it's wholesale price
        /// </summary>
        [ReadOnly(true)]
        [Display(Name = "Mayoreo", AutoGenerateField = true)]
        public bool IsWholeSale { get; set; }
        /// <summary>
        /// Flag that indicates if the sale's been sold on credit
        /// </summary>
        [Display(Name = "Crédito", AutoGenerateField = false)]
        public bool IsCredit { get; set; }
        /// <summary>
        /// Days to liquidate the sell if it's been done on credit
        /// </summary>
        [Display(Name = "Días Crédito", AutoGenerateField = false)]
        public int CreditDays { get; set; }
        /// <summary>
        /// Value of discount
        /// </summary>
        [Display(Name = "Descuento", AutoGenerateField = false)]
        public double Discount { get; set; }
        /// <summary>
        /// Type of IVA
        /// </summary>
        [Display(AutoGenerateField = false)]
        public int IVAType { get; set; }
        /// <summary>
        /// SubtTotal value
        /// </summary>
        [Display(Name = "SubTotal", AutoGenerateField = true, Description = "Template")]
        public double SubTotal { get; set; }
        /// <summary>
        /// Total value
        /// </summary>
        [Display(AutoGenerateField = true, Name ="Total", Description = "Template")]
        public double Total { get; set; }
        /// <summary>
        /// Payment done to the sale
        /// </summary>
        [Display(AutoGenerateField = true, Description = "Validate", Name = "Abonos")]
        public Double Payments
        {
            get
            {
                double payments = 0;
                SalePayments.ToList().ForEach(a => payments += a.Payment);
                return payments;
            }
        }
        /// <summary>
        /// Total value
        /// </summary>
        [Display(AutoGenerateField = true, Description = "Validate", Name = "Abonar")]
        public String Pay { get; set; }
        /// <summary>
        /// Total value
        /// </summary>
        [Display(AutoGenerateField = true, Description ="Template",Name ="Ver venta")]
        public String View{ get; set; }
        /// <summary>
        /// Map foreign instance of Client
        /// </summary>
        [Display(AutoGenerateField = false)]
        public virtual Client Client { get; set; }
        /// <summary>
        /// Map foreign instance of User
        /// </summary>
        [Display(AutoGenerateField = false)]
        public virtual User User { get; set; }
        /// <summary>
        /// Map foreing instance of SalePayment
        /// </summary>
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [Display(AutoGenerateField = false)]
        public virtual ICollection<SalePayment> SalePayments { get; set; }
        /// <summary>
        /// Map foreign instance of SaleProduct
        /// </summary>
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [Display(AutoGenerateField = false)]
        public virtual ICollection<SaleProduct> SaleProducts { get; set; }
        #endregion
    }
}
