//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeposWPF.Model
{
    using System;
    using System.Collections.Generic;
    /// <summary>
    /// Class that maps a Sale to the database
    /// </summary>
    public partial class Sale
    {
        #region Constructors
        /// <summary>
        /// Initialize current instance
        /// </summary>
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sale()
        {
            this.SalePayments = new HashSet<SalePayment>();
            this.SaleProducts = new HashSet<SaleProduct>();
        }
        #endregion
        #region Declaration
        /// <summary>
        /// Identifier of current instance
        /// </summary>
        public long ID { get; set; }
        /// <summary>
        /// Foreign ID of client
        /// </summary>
        public long Client_ID { get; set; }
        /// <summary>
        /// Foreign ID of user
        /// </summary>
        public string User_ID { get; set; }
        /// <summary>
        /// Date of transaction
        /// </summary>
        public System.DateTime Date { get; set; }
        /// <summary>
        /// Flag that indicates if it's wholesale price
        /// </summary>
        public bool IsWholeSale { get; set; }
        /// <summary>
        /// Flag that indicates if the sale's been sold on credit
        /// </summary>
        public bool IsCredit { get; set; }
        /// <summary>
        /// Days to liquidate the sell if it's been done on credit
        /// </summary>
        public int CreditDays { get; set; }
        /// <summary>
        /// Value of discount
        /// </summary>
        public double Discount { get; set; }
        /// <summary>
        /// Type of IVA
        /// </summary>
        public int IVAType { get; set; }
        /// <summary>
        /// SubtTotal value
        /// </summary>
        public double SubTotal { get; set; }
        /// <summary>
        /// Total value
        /// </summary>
        public double Total { get; set; }
    
        /// <summary>
        /// Map foreign instance of Client
        /// </summary>
        public virtual Client Client { get; set; }
        /// <summary>
        /// Map foreign instance of User
        /// </summary>
        public virtual User User { get; set; }
        /// <summary>
        /// Map foreing instance of SalePayment
        /// </summary>
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalePayment> SalePayments { get; set; }
        /// <summary>
        /// Map foreign instance of SaleProduct
        /// </summary>
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SaleProduct> SaleProducts { get; set; }
        #endregion
    }
}
