//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeposWPF.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    /// <summary>
    /// Class that maps a SalePayment to the database
    /// </summary>
    public partial class SalePayment
    {
        #region Definition
        /// <summary>
        /// Identifier of the current instance
        /// </summary>
        [Display(AutoGenerateField = false)]
        public long ID { get; set; }
        /// <summary>
        /// Foreign ID of sale
        /// </summary>
        [Display(Name="ID Venta",AutoGenerateField = false)]
        public long Sale_ID { get; set; }
        /// <summary>
        /// Foreign ID of user
        /// </summary>
        [Display(Name = "Registrado", AutoGenerateField = true)]
        public string User_ID { get; set; }
        /// <summary>
        /// Date of transaction
        /// </summary>
        [Display(Name = "Fecha", AutoGenerateField = true)]
        public System.DateTime Date { get; set; }
        /// <summary>
        /// Value of payment
        /// </summary>
        [Display(Name = "Abono", AutoGenerateField = false)]
        public double Payment { get; set; }
        /// <summary>
        /// Value of payment done formatted
        /// </summary>
        [Display(Name = "Abono", AutoGenerateField = true)]
        public String PaymentFormatted
        {
            get
            {
                return Payment.ToString("C");
            }
        }

        /// <summary>
        /// Map foreign instance of sale
        /// </summary>
        [Display(AutoGenerateField = false)]
        public virtual Sale Sale { get; set; }
        /// <summary>
        /// Map foreign instance of user
        /// </summary>
        [Display(AutoGenerateField = false)]
        public virtual User User { get; set; }
        #endregion
    }
}
