//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeposWPF.Model
{
    using System;
    using System.Collections.Generic;
    /// <summary>
    /// Class that maps a SalePayment to the database
    /// </summary>
    public partial class SalePayment
    {
        #region Definition
        /// <summary>
        /// Identifier of the current instance
        /// </summary>
        public long ID { get; set; }
        /// <summary>
        /// Foreign ID of sale
        /// </summary>
        public long Sale_ID { get; set; }
        /// <summary>
        /// Foreign ID of user
        /// </summary>
        public string User_ID { get; set; }
        /// <summary>
        /// Date of transaction
        /// </summary>
        public System.DateTime Date { get; set; }
        /// <summary>
        /// Value of payment
        /// </summary>
        public double Payment { get; set; }
        
        /// <summary>
        /// Map foreign instance of sale
        /// </summary>
        public virtual Sale Sale { get; set; }
        /// <summary>
        /// Map foreign instance of user
        /// </summary>
        public virtual User User { get; set; }
        #endregion
    }
}
