//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeposWPF.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    /// <summary>
    /// Class that maps a SaleProduct to the database
    /// </summary>
    public partial class SaleProduct
    {
        #region Definition
        /// <summary>
        /// Foreign ID of sale
        /// </summary>
        [Display(AutoGenerateField = false)]
        public long Sale_ID { get; set; }
        /// <summary>
        /// Foreign ID of product
        /// </summary>
        [Display(Name = "Producto", AutoGenerateField = true, Description = "Template")]
        public string Product_ID { get; set; }
        /// <summary>
        /// Quantity of sold products
        /// </summary>
        [Display(Name = "Cantidad", AutoGenerateField = true)]
        public double Quantity { get; set; }
        /// <summary>
        /// Price of product
        /// </summary>
        [Display(Name="Precio", AutoGenerateField = true)]
        public double Price { get; set; }

        /// <summary>
        /// Map foreign instance of sale
        /// </summary>
        [Display(AutoGenerateField = false)]
        public virtual Sale Sale { get; set; }
        #endregion
    }
}
