//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeposWPF.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    /// <summary>
    /// Class that maps a user to the database
    /// </summary>
    public partial class User
    {
        #region Constructors
        /// <summary>
        /// Initialize the current object
        /// </summary>
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.ProductPrices = new HashSet<ProductPrice>();
            this.Purchases = new HashSet<Purchase>();
            this.PurchasePayments = new HashSet<PurchasePayment>();
            this.Sales = new HashSet<Sale>();
            this.SalePayments = new HashSet<SalePayment>();
            this.IsAlive = true;
            this.Birth = DateTime.Today;
        }
        #endregion
        #region Definition
        /// <summary>
        /// Identifier for the local instance
        /// </summary>
        [Display(Name="ID",AutoGenerateField = true)]
        public string ID { get; set; }
        /// <summary>
        /// Password of the user
        /// </summary>
        [Display(Name="Password",AutoGenerateField = false)]
        public string Password { get; set; }
        /// <summary>
        /// Type of user, indicating its privileges
        /// </summary>
        [Display(Name="Tipo",AutoGenerateField = true,Description ="Template")]
        public int Type { get; set; }
        /// <summary>
        /// Type of user, indicating its privileges as a string
        /// </summary>
        [Display(AutoGenerateField = false)]
        public String TypeName {
            get
            {
                String type = String.Empty;
                switch (Type)
                {
                    case 0:
                        type = "Administrador";
                        break;
                    case 1:
                        type = "Vendedor de mostrador";
                        break;
                }
                return type;
            }
        }
        /// <summary>
        /// Date of user's birth in the system
        /// </summary>
        [Display(AutoGenerateField = false)]
        public System.DateTime Birth { get; set; }
        /// <summary>
        /// Date of user's death in the system
        /// </summary>
        [Display(AutoGenerateField = false)]
        public System.DateTime Death { get; set; }
        /// <summary>
        /// Flag that indicates if the user is still active
        /// </summary>
        [Display(AutoGenerateField = false)]
        public bool IsAlive { get; set; }

        /// <summary>
        /// List of the times a user has updated a product's value
        /// </summary>
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [Display(AutoGenerateField = false)]
        public virtual ICollection<ProductPrice> ProductPrices { get; set; }
        /// <summary>
        /// List of purchases done by the user
        /// </summary>
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [Display(AutoGenerateField = false)]
        public virtual ICollection<Purchase> Purchases { get; set; }
        /// <summary>
        /// List of purchases payments done by the user
        /// </summary>
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [Display(AutoGenerateField = false)]
        public virtual ICollection<PurchasePayment> PurchasePayments { get; set; }
        /// <summary>
        /// List of sales done by the user
        /// </summary>
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [Display(AutoGenerateField = false)]
        public virtual ICollection<Sale> Sales { get; set; }
        /// <summary>
        /// List of sales payments done by the user
        /// </summary>
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [Display(AutoGenerateField = false)]
        public virtual ICollection<SalePayment> SalePayments { get; set; }
        #endregion
    }
}
